version: '3'

services:

  mailserver:
    image: analogic/poste.io
    container_name: mailserver-cristianriverinDev
    restart: always
    network_mode: "host"
    expose:
      - "25"
      - "80"
      - "443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    environment:
      - TZ=America/La_Paz
      - h=mail.cristianriverin.com #==> Direccion del servidor de mail hosting
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - DISABLE_CLAMAV=TRUE
    volumes:
      - /mnt/mail:/data