version: '3'

services:

  mailserver:
    image: analogic/poste.io
    container_name: mailserver-cristianriverinDev
    restart: always
    network_mode: "host"
    extra_hosts:
      - "mail.cristianriverin.com:45.79.25.159" #==> Direccion del servidor de mail hosting
    expose:
      - "25"
      - "8080"
      - "4443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    environment:
      - TZ=America/La_Paz
      - h=mail.cristianriverin.com #==> Direccion del servidor de mail hosting
      - HTTP_PORT=8080
      - HTTPS_PORT=4443
      - DISABLE_CLAMAV=TRUE
    volumes:
      - /var/www/mail:/data