version: '3.9'

services:
  mail-server:
    image: analogic/poste.io
    container_name: mail-server.cristianriverin.com
    restart: always
    network_mode: "host"
    expose:
      - 25
      - 8181
      - 4443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - /root/mail-data:/data
    environment:
      - TZ=America/La Paz
      - h=mail.cristianriverin.com
      - HTTP_PORT=8181
      - HTTPS_PORT=4443